//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("Rmdy.Android.Wowza")]
[assembly: AssemblyCompany("Rmdy")]
[assembly: AssemblyProduct("Rmdy.Android.Wowza")]
[assembly: AssemblyVersion("1.5.0.1")]
[assembly: AssemblyFileVersion("1.5.0.1")]
[assembly: AssemblyInformationalVersion("1.5.0.1-beta")]
[assembly: AssemblyCopyright("Copyright (c) 2020, Rmdy")]

