//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyTitle("x3factr.Platform.Droid.Wowza")]
[assembly: AssemblyCompany("3factr")]
[assembly: AssemblyProduct("x3factr.Platform.Droid.Wowza")]
[assembly: AssemblyVersion("1.5.0.1")]
[assembly: AssemblyFileVersion("1.5.0.1")]
[assembly: AssemblyInformationalVersion("1.5.0.1-beta")]
[assembly: AssemblyCopyright("Copyright (c) 2018, 3factr")]

